apiVersion: v1
kind: Service
metadata:
  labels:
    run: service1
  name: service1
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    name: http-service1
  selector:
    run: helloworld
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service2
  name: service2
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
    name: http-service2
  selector:
    run: hellored
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service4
  name: service4
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: http-service4
  selector:
    run: hello-python
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service3
  name: service3
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8083
    name: http-service3
  selector:
    run: hub
  type: ClusterIP
