apiVersion: v1
kind: Service
metadata:
  labels:
    run: service1
  name: service1
  namespace: petclinic
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    name: http-service1
  selector:
    run: helloworld
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service4
  name: service4
  namespace: petclinic
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: http-service4
  selector:
    run: hello-python
  type: ClusterIP
