kind: ConfigMap
apiVersion: v1
metadata:
  name: hellorest
  namespace: demo7
data:
  spring.sleuth.enabled: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hellored
  namespace: demo7
data:
  spring.sleuth.enabled: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hub
  namespace: demo7
data:
  spring.sleuth.enabled: "true"
  hub.urls: "http://service1/hello,http://service2/hello,http://service4"
